# Generated by Django 3.1 on 2020-08-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'ordering': ['nome_fantasia'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='nome',
            new_name='nome_fantasia',
        ),
        migrations.AddField(
            model_name='empresas',
            name='razao_social',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
