# Generated by Django 3.1 on 2020-08-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200809_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='funcionario',
            field=models.ManyToManyField(blank=True, null=True, to='core.Funcionarios'),
        ),
    ]
