# Generated by Django 3.1 on 2020-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200810_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='funcionario',
            field=models.ManyToManyField(blank=True, null=True, related_name='empresas', to='core.Funcionarios'),
        ),
    ]
