# Generated by Django 3.1 on 2020-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200810_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='empresa',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='core.Empresas'),
        ),
    ]
